tasks:
  # - name: start-localstack
  #   env:
  #     AWS_ACCESS_KEY_ID: "test"
  #     AWS_SECRET_ACCESS_KEY: "test"
  #     AWS_DEFAULT_REGION: "us-east-1"
  #   init: |
  #           python -m pip install localstack
  #   command: |
  #     . ~/.bash_profile
  #     docker network create localstack
  #     localstack start
  - name: install-awslocal
    env:
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_DEFAULT_REGION: "us-east-1"
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      python -m pip install awscli-local
  - name: install-awssamcli
      cd /workspace
      mkdir install-awssam
      cd install-awssam
      curl "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip" -o "awssamcli.zip"
      unzip awssamcli.zip
      sudo ./install --update
ports:
  - port: 4510-4559
    onOpen: ignore
  - port: 4566
    onOpen: ignore
  - port: 53
    onOpen: ignore
  - port: 443
    onOpen: ignore
